### ISSUE TITLE
UMD 

### ISSUE THREAD

**Issue by gustavnikolaj** [One-com/knockout.list#16]
The UMD factory pattern here confuses me. Is there any good reason why we rely on a global jQuery here, instead of having the module loader provide it?

https://github.com/One-com/knockout.list/blob/master/lib/knockout.list.js#L17-L23

Seems like an odd choice to use a global for jQuery and use a module loader for knockout.

Any objections to me aligning this to use the module loaders if possible, and only rely on a global jQuery when necessary?

@sunesimonsen @mwoc @gertsonderby @papandreou @birkestroem

**Comment by sunesimonsen** [comment]
Sounds like a reasonable change.

**Comment by gustavnikolaj** [comment]
I'm not an owner of the package on npm. v1.1.5 is pushed to the repo, but not yet published.

**Comment by sunesimonsen** [comment]
I can give you rights when I'm at a computer

**Comment by sunesimonsen** [comment]
I added you as owner.

**Comment by gustavnikolaj** [comment]
Thank you @sunesimonsen ! :rocket:
